--permission for silver layer to access the data in bronze layer 

GRANT SELECT ON BRONZE.CRM_CUST_INFO TO SILVER;
GRANT SELECT ON BRONZE.CRM_PRD_INFO TO SILVER;
GRANT SELECT ON BRONZE.CRM_SALES_DETAILS TO SILVER;
GRANT SELECT ON BRONZE.ERP_CUST_AZ12 TO SILVER;
GRANT SELECT ON BRONZE.ERP_LOC_A101 TO SILVER;
GRANT SELECT ON BRONZE.ERP_PX_CAT_G1V2 TO SILVER;


--permission for gold layer to access the data in silver layer

GRANT SELECT ON SILVER.CRM_CUST_INFO TO GOLD;
GRANT SELECT ON SILVER.CRM_PRD_INFO TO GOLD;
GRANT SELECT ON SILVER.CRM_SALES_DETAILS TO GOLD;
GRANT SELECT ON SILVER.ERP_CUST_AZ12 TO GOLD;
GRANT SELECT ON SILVER.ERP_LOC_A101 TO GOLD;
GRANT SELECT ON SILVER.ERP_PX_CAT_G1V2 TO GOLD;
